sudo: required

services:
- docker

env:
  DOCKER_COMPOSE_VERSION: '1.11.1'

before_install:
  # Print out the current docker-compose version. Once this reports 1.6+ then we
  # do not need the following steps.
  - docker-compose --version

  # As of the writing of this script Travis has docker-compose v1.4.2, we need
  # to update it to 1.8+. $DOCKER_COMPOSE_VERSION is provide from the `env`
  # above.
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose

  - echo ${DOCKER_COMPOSE_VERSION}

  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # Check that docker-compose is now running the latest version (or at least the
  # one we specified). This is not to be confused with the version we printed
  # before doing the update.
  - docker-compose --version

  # Setup your application stack. You may need to tweak these commands if you
  # doing out-of-the-ordinary docker-compose builds.
  - docker-compose pull
  - docker-compose build
  - docker-compose start

script:
  - docker-compose -f docker-compose-travis.yml up --build -d

after_script:
  - docker-compose -f docker-compose-travis.yml down

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- ./scripts/docker_ci.sh

env:
  matrix:
    secure: XoedU3vnz5Er1mmqOkZ4VID6xLig7meHCYMzP4MUIdxPJetZ2jRjFWm4rj+yMoREZBpXD46scFFPQ+BFEftmP0TU4/Gos49qlwxjGrDsEVVNw7XS70nyibBspvlurrMNuKogvRl+iNk/WP0a9t6uYFDdHQJ8AKlEZfKilkycI6tO4DaYXddRTfdwcPDQ4EjVjSJJp4ivhaPwqDVsNSg8rTzhyRMcCRg8UZ6IAdUOK5K6mGf5cBloRgjztoHP2hMaHS44C8cRcY9VEETfpxNYlc/XRAVBLHCN7JNQE/QN4GOVxtbXuZKKSCFJX0fs8NZAWKOiKA/4iOeSkQBljrRXFjZvpHcsciVxkjNvr3csaV6mH/LsOHl8ZyKvoEOXx5/NlbasLyiElnskMXQMhvXIJruSR/18uk3+LFrSBbczbw0+Lenu5zpsEjZShe9ijBgCAdr68iJwIxM1AicoNDbByGvzSaTQ8ISuO+TLiu3PupgTN6oE8z65GlWOA5abzqrroXprcMCGnMD9QVbhaz2ZxX9SuPNC40DEUnoisMuea6MIOF7PfHsEzrWoCdepaYC5JXZV6i1E4bS4zI4DsOa9Hu/Odi66nREn0qPht3BWs3p4iFrxLnlpMbNf0cSPvC1GUsDcplwDEuNxSac7tYpZA4xpx8HxjHns/8Jd0FXlKcE=