services:
- docker

before_install:
  - pip install docker-compose

script:
  - docker-compose -f docker-compose-travis.yml build travis-tests
  - docker-compose -f docker-compose-travis.yml run travis-tests

after_script:
  - docker-compose -f docker-compose-travis.yml down -v

after_success:
  - bash ./scripts/ci-deployment/deploy.sh
