services:
- docker

before_install:
  - yarn global add greenkeeper-lockfile@1
  - pip install docker-compose

before_script: greenkeeper-lockfile-update

script:
  - docker-compose -f docker-compose-travis.yml build travis-tests
  - docker-compose -f docker-compose-travis.yml run travis-tests

after_script:
  - docker-compose -f docker-compose-travis.yml down -v
  - greenkeeper-lockfile-upload

after_success: bash ./scripts/ci-deployment/deploy.sh
