version: '2.1'

services:

  travis-tests:
    build:
      context: .
      args:
        NODE_ENV: development
    command: yarn run travis
    user: root
    volumes:
      - .:/code
      - test-deps:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: development
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
      - mongodb-pharmacy:mongo

  mongodb-pharmacy:
    image: "nhsuk/pharmacy-db:${MONGO_IMAGE_TAG-latest}"

volumes:
  test-deps:
