version: '2.1'

services:

  api-test:
    build:
      context: .
      args:
        NODE_ENV: test
    command: yarn run watch-test
    environment:
      NODE_ENV: test
    user: root
    volumes:
      - .:/code
      - api-test-deps:/code/node_modules
    links:
      - mongodb-pharmacy-test:mongo

  mongodb-pharmacy-test:
    image: "nhsuk/pharmacy-db:${MONGO_IMAGE_TAG-latest}"

volumes:
  api-test-deps:
