version: '2.1'

services:

  test-ci:
    build:
      context: .
      args:
        NODE_ENV: development
    command: yarn run test-ci
    user: root
    volumes:
      - .:/code
      - test-ci-deps:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: development
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
      - pharmacy-db-elastic-test:es

  pharmacy-db-elastic-test:
    image: "nhsuk/elasticsearch-updater-snapshot:20171213"

volumes:
  test-ci-deps:
