version: '2.1'

services:

  nearby-services-api-tests:
    build:
      context: .
      args:
        NODE_ENV: development
    command:
      sh -c "npm run git-hook && npm run snyk-test && npm run upload-coverage-coveralls"
    user: root
    volumes:
      - .:/code
      - test-deps:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: development
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
      - mongodb-pharmacy:mongo

  mongodb-pharmacy:
    image: "nhsuk/mongodb-pharmacy:${MONGO_IMAGE_TAG-latest}"

volumes:
  test-deps:
