version: '2.1'

services:

  nearby-services-api:
    build:
      context: .
      args:
        NODE_ENV: development
    command: yarn run start-watch
    ports:
      - 3001:3001
    volumes:
      - .:/code
      - api-deps:/code/node_modules
    environment:
      DATETIME: ${DATETIME}
      NODE_ENV: development
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_LOG_LEVEL: ${NEW_RELIC_LOG_LEVEL}
    links:
      - pharmacy-db-elastic:es

  pharmacy-db-elastic:
    image: "nhsuk/elasticsearch-updater-snapshot:20171213"

volumes:
  api-deps:
