version: '2.1'

services:

  nearby-services-api:
    build:
      context: .
      args:
        NODE_ENV: development
    command:
      sh -c "npm run git-hook && npm run snyk-test && npm run upload-coverage-coveralls"
    volumes:
      - ./:/code
      - api-travis-test-deps:/code/node_modules
    environment:
      NODE_ENV: development
      TRAVIS: 'true'
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
    links:
      - mongodb-pharmacy:mongo

  mongodb-pharmacy:
    image: "nhsuk/mongodb-pharmacy:${MONGO_IMAGE_TAG-latest}"

volumes:
  api-travis-test-deps: