version: '2.1'

services:
  c2s-frontend:
    image: "nhsuk/connecting-to-services"
    environment:
      NODE_ENV: development
      HOTJAR_ANALYTICS_TRACKING_ID: ${HOTJAR_ANALYTICS_TRACKING_ID-0}
      GOOGLE_ANALYTICS_TRACKING_ID: ${GOOGLE_ANALYTICS_TRACKING_ID}
      WEBTRENDS_ANALYTICS_TRACKING_ID: ${WEBTRENDS_ANALYTICS_TRACKING_ID-WT1}
      API_BASE_URL: 'http://nearby-services-api:3001'
    ports:
      - 3000:3000
    links:
    - nearby-services-api:nearby-services-api

  nearby-services-api:
    build:
      context: .
      args:
        NODE_ENV: development
    command: yarn run start-watch
    ports:
      - 3001:3001
    volumes:
      - .:/code
      - api-deps:/code/node_modules
    environment:
      NODE_ENV: development
      DATETIME: '${DATETIME}'
    links:
      - pharmacy-db-elastic:es

  pharmacy-db-elastic:
    image: "nhsuk/elasticsearch-updater-snapshot:20170905"


volumes:
  api-deps:
