version: '2.1'

services:

  nearby-services-api:
    build:
      context: .
      args:
        NODE_ENV: development
    command: yarn run start-watch
    ports:
      - 3001:3001
    volumes:
      - .:/code
      - api-deps:/code/node_modules
    environment:
      NODE_ENV: development
    links:
      - pharmacy-db-elastic:es

  pharmacy-db-elastic:
    image: "nhsuk/elasticsearch-updater-snapshot:20170921"

volumes:
  api-deps:
