version: '2.1'

services:

  test:
    build:
      context: .
      args:
        NODE_ENV: test
    command: yarn run test-watch
    environment:
      NODE_ENV: test
    user: root
    volumes:
      - .:/code
      - api-test-deps:/code/node_modules
    links:
      - pharmacy-db-test:mongo

  pharmacy-db-test:
    image: "nhsuk/pharmacy-db:${MONGO_IMAGE_TAG-0.1.0}"

volumes:
  api-test-deps:
