version: '2'

services:

  api-test:
    build:
      context: .
      args:
        NODE_ENV: test
    command: sh -c 'npm run git-hook && npm run snyk-test && npm run watch-test'
    environment:
      SNYK_TOKEN: ${SNYK_TOKEN-REPLACEME}
    volumes:
      - ./:/code
      - api-test-deps:/code/node_modules
    links:
      - mongodb-pharmacy-test:mongo

  mongodb-pharmacy-test:
    image: "nhsuk/mongodb-pharmacy:${MONGO_IMAGE_TAG-latest}"

volumes:
  api-test-deps:
