version: '2.1'

services:

  test:
    build:
      context: .
      args:
        NODE_ENV: test
    command: yarn run test-watch
    environment:
      NODE_ENV: test
    user: root
    volumes:
      - .:/code
      - api-test-deps:/code/node_modules
    links:
      - pharmacy-db-elastic-test:es

  pharmacy-db-elastic-test:
    image: "nhsuk/elasticsearch-updater-snapshot:20170921"

volumes:
  api-test-deps:
