version: '2.1'

services:

  nearby-services-api:
    build:
      context: .
      args:
        NODE_ENV: development
    command: yarn run watch-dev
    ports:
      - 3001:3001
    volumes:
      - .:/code
      - api-deps:/code/node_modules
    environment:
      NODE_ENV: development
    links:
      - pharmacy-db:mongo

  pharmacy-db:
    image: "nhsuk/pharmacy-db:${MONGO_IMAGE_TAG-0.1.0}"

volumes:
  api-deps:
