version: '2'

services:

  nearby-services-api:
    image: "nhsuk/nearby-services-api:${DOCKER_IMAGE_TAG}"
    environment:
      NODE_ENV: production
      MONGODB_HOST: pharmacy-db.pharmacy-db
    labels:
      traefik.enable: true
      traefik.frontend.rule: $TRAEFIK_RULE
      traefik.port: 3001
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity: "container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}"
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: nearby-services-api
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
        splunk-format: json
