version: '2'

services:

  nearby-services-api:
    image: "nhsuk/nearby-services-api:${DOCKER_IMAGE_TAG}"
    environment:
      ES_HOST: ${ES_HOST}
      ES_INDEX: ${ES_INDEX}
      ES_PORT: ${ES_PORT}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_LOG_LEVEL: ${NEW_RELIC_LOG_LEVEL}
      NODE_ENV: production
    labels:
      traefik.enable: true
      traefik.frontend.rule: $TRAEFIK_RULE
      traefik.backend: ${RANCHER_STACK_NAME}-nearby-services-api
      traefik.port: 3001
      prometheus.port: 3001
      prometheus.monitoring: true
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: "io.rancher.stack_service.name=$${stack_name}/$${service_name}"
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: nearby-services-api
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
        splunk-format: json
