version: '2'

services:

  nearby-services-api:
    scale: 1
    health_check:
      response_timeout: 60000
      healthy_threshold: 2
      port: 3001
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 20000
      strategy: recreate
      request_line: GET "/nearby?latitude=53.800755&longitude=-1.549077" "HTTP/1.0"
      reinitializing_timeout: 60000
    start_on_create: true
