version: '2'

services:

  nearby-services-api:
    scale: $INITIAL_CONTAINER_SCALE
    health_check:
      response_timeout: 60000
      healthy_threshold: 2
      port: 3001
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 20000
      strategy: recreate
      reinitializing_timeout: 60000
    start_on_create: true
